# Generated by Django 5.0.6 on 2024-05-29 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telecom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelecomData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hyzmat', models.CharField(max_length=20, verbose_name='Hyzmaty saýlaň')),
                ('sahs', models.CharField(max_length=20, verbose_name='Şahsy saýlaň')),
                ('ady', models.CharField(max_length=50, verbose_name='Ady, familiýasy')),
                ('salgy', models.CharField(max_length=250, verbose_name='Öý salgyňyz')),
                ('mobil_belgi', models.IntegerField(verbose_name='Telefon belgiňiz')),
                ('telefon_belgi', models.IntegerField(verbose_name='Öý telefon belgiňiz')),
                ('mesele', models.TextField(max_length=900, verbose_name='Meseläňiz')),
                ('sene', models.DateTimeField(verbose_name='Wagty saýlaň')),
                ('date_save', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ýüz tutma',
                'verbose_name_plural': 'Ýüz tutmalar',
            },
        ),
        migrations.DeleteModel(
            name='Articles',
        ),
    ]
